### ISSUE TITLE
Table not rendered in slide show

### ISSUE THREAD

**Issue by sheiksadique** [coddingtonbear/obsidian-csv-table#18]
The table does not get rendered when in slideshow/presentation mode although it gets rendered perfectly well when being displayed in normal markdown view.

Is there something special that needs to be done for slideshows?

**Comment by coddingtonbear** [comment]
I'm afraid the built-in presentation mode doesn't support the API used by this (and other) Obsidian plugins (see also, e.g.: https://github.com/blacksmithgu/obsidian-dataview/issues/243 ).  Unfortunately, since this limitation can't be addressed by changes in this plugin, I think my hands are tied and I will be closing this issue.

This is probably a thing that should be posted as a bug in Obsidian itself, but I'm not exactly sure where their bug tracker is; if you do find a bug tracker that you post this issue to for them, please post a link to the issue you post here so future folks can know where to look for updates.

Cheers!
