### ISSUE TITLE
CSV file 'xyz.csv' could not be found.

### ISSUE THREAD

**Issue by gemisigo** [coddingtonbear/obsidian-csv-table#3]
Do you have any kind of logs I could turn on and check? Whatever I do I get the error message in the title. The plugin is definitely able to work (it did when I installed it in an empty vault) but it does not when I install it in my own vault. I disabled all the other plugins to filter out interference but it still refused to yield. I suspect vault path is the culprit but am at a loss here.

**Comment by dukatheduke** [comment]
It seems that a path relative to the vault folder is required. So, try with `source: Files/OID.csv` if the `MAIN-BD` is your vault location.

**Comment by coddingtonbear** [comment]
I _believe_ @dukatheduke is correct in that it just needs to be the path relative to the root of your repository, but do feel free to respond if you're still having trouble.  Although I've tested this on Windows, I have to admit that that testing has been very much surface-level, and there's room for problems to crop up there.

**Comment by grimsius** [comment]
> It seems that a path relative to the vault folder is required. So, try with `source: Files/OID.csv` if the `MAIN-BD` is your vault location.

Hi, thx!
It turned out to be done like this:

```csvtable
source: "Files/OID.csv"
```

P.S.
I couldn’t get it to work at first so I’ll offer a couple use notes for other users that can’t get it to work.

1. The source file name has to be in double quotes regardless of whether or not there are spaces in the file name, like source: "my_csv_file.csv" The README demonstrates no quotes, source: my_csv_file.csv but in practice, that doesn’t work.
2. The plugin does not read from the same directory as the current .md that is calling the csv. This plugin reads from your vault’s root directory. That surprised me. I would have expected the standard for relative file referencing, using ../ to move up a directory, and ./ to point to the vault (root) directory.
3. Also, if you want to keep your CSV in the same directory as the .md file that’s calling it, then you must build out the address with forward slashes
    source: "/Documentation/my_csv_file.csv"
    not the backwards slashes that are default for a windows system.
    source: "\Documentation\my_csv_file.csv"

I’m using Windows 10
