### ISSUE TITLE
csv file 'xxxxx.csv' could not be found

### ISSUE THREAD

**Issue by oscampo** [coddingtonbear/obsidian-csv-table#6]
Hi,
I recently installed your plugin, but no matter where I put my CSV file, I have the same error: CSV file 'xxxxx.csv' could not be found.
I have Obsidian V0,13.6 on windows 11 (Build 2021.11.21.25838867)

**Comment by coddingtonbear** [comment]
The path to the csv file should be relative to your repository root; can you provide a little more information about what you have tried and where this CSV is in repo?

Although I did test this on windows long ago, there is definitely room for there being a bug on that platform since it’s not one I regularly use and there has been a report before (#3).

**Comment by oscampo** [comment]
Thanks! Using a path relative to the vault folder was enough to fix it.
